# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90b6cd825c2d849d8f55208b243babb7eda3999bcd3ccaa5725149d250bf7f40811f4bd912dcefb78f214e149c8330cc975531c10841a1c6a97b9fbf82dbd37f

test:
  secret_key_base: e747761e69902563da6136d0f8a82743b87cede428ba0cd86b18f143088f5e5e0c4ffd28829472ef67b3714b484176622de38efef34afb31ef3202792059c249

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
